### ISSUE TITLE
Pre-trained checkpoints?

### ISSUE THREAD

**Issue by Dev-iL** [pquochuy/sasegan#1]
Thank you for making your implementation available!

Would it be possible to upload at least some of the checkpoint weights so that readers such as myself could easily evaluate the tool on their own data?

**Comment by pquochuy** [comment]
Hi, thanks for your interest. I have just added the trained model checkpoints which you can download from here: https://zenodo.org/record/4288589

**Comment by shrutikshirsagar** [comment]
Hey, thanks for providing your code. Could you please share the .yml envirnment file, or exact version of python, and other libraries that have been used for this implementation? It would be really great if you could share it! Thanks again!

**Comment by pquochuy** [comment]
Hi, if you use tensorflow 1 version

python 3.6
tensorflow_gpu 1.9
numpy==1.1.3
scipy==1.0.0
